[options]
name = "boron_nitride_"
weak_collision_order = 0
num_threads = 4

[material_parameters]
energy_unit = "EV"
mass_unit = "AMU"
Eb = [ 0.0, 0.0,]
Es = [ 5.76, 0.0,]
Ec = [ 1.0, 1.0,]
Z = [ 5, 7,]
m = [ 10.811, 14,]

[particle_parameters]
length_unit = "MICRON"
energy_unit = "EV"
mass_unit = "AMU"
N = [ 10000 ]
m = [ 1.008 ]
Z = [ 1 ]
E = [ 1000.0 ]
Ec = [ 1.0 ]
Es = [ 10.0 ]
pos = [ [ 0.0, 0.0, 0.0,] ]
dir = [ [ 0.9999999999984769, 1.7453292519934434e-6, 0.0,] ]

[geometry_input]
length_unit = "ANGSTROM"
electronic_stopping_correction_factor = 1.0
densities = [0.065, 0.065]
