[options]
name = "tungsten_tiles_"
track_trajectories = true
track_recoils = true
track_recoil_trajectories = true
write_buffer_size = 8000
weak_collision_order = 0
suppress_deep_recoils = false
high_energy_free_flight_paths = false
num_threads = 4
num_chunks = 5
use_hdf5 = false
electronic_stopping_mode = "LOW_ENERGY_NONLOCAL"
mean_free_path_model = "LIQUID"
interaction_potential = [["KR_C"]]
scattering_integral = [["MENDENHALL_WELLER"]]
root_finder = [[{"NEWTON"={max_iterations=100, tolerance=1E-3}}]]
track_displacements = false
track_energy_losses = false

[material_parameters]
energy_unit = "EV"
mass_unit = "AMU"
Eb = [ 3.0,]
Es = [ 8.79,]
Ec = [ 1.0,]
Z = [ 74 ]
m = [ 183.84 ]
interaction_index = [0]
surface_binding_model = {"PLANAR"={calculation="TARGET"}}
bulk_binding_model = "AVERAGE"

[particle_parameters]
length_unit = "1e-8"
energy_unit = "EV"
mass_unit = "AMU"
N = [ 10 ]
m = [ 4.008 ]
Z = [ 2 ]
E = [ 250.0 ]
Ec = [ 1.0 ]
Es = [ 0.0 ]
pos = [ [ 0.35, 1.0, 0.5,] ]
dir = [ [ 0.98, -0.3, 0.0,] ]
interaction_index = [ 0 ]

[geometry_input]
length_unit = "1e-8"
electronic_stopping_correction_factor = 1.0
densities = [60000]
vertices = [
  [0.00000000, 0.00000000, 0.00000000],
  [0.00000000, 0.00000000, 0.20000000],
  [0.00000000, 0.00000000, 0.40000000],
  [0.00000000, 0.00000000, 0.60000000],
  [0.00000000, 0.00000000, 0.80000000],
  [0.00000000, 0.00000000, 1.00000000],
  [0.00000000, 1.00000000, 0.00000000],
  [0.00000000, 1.00000000, 0.20000000],
  [0.00000000, 1.00000000, 0.40000000],
  [0.00000000, 1.00000000, 0.60000000],
  [0.00000000, 1.00000000, 0.80000000],
  [0.00000000, 1.00000000, 1.00000000],
  [0.20000000, 0.55000000, 0.00000000],
  [0.20000000, 0.55000000, 1.00000000],
  [0.40000000, 0.20000000, 0.00000000],
  [0.40000000, 0.20000000, 0.20000000],
  [0.40000000, 0.20000000, 0.40000000],
  [0.40000000, 0.20000000, 0.60000000],
  [0.40000000, 0.20000000, 0.80000000],
  [0.40000000, 0.20000000, 1.00000000],
  [0.40000000, 1.00000000, 0.00000000],
  [0.40000000, 1.00000000, 0.20000000],
  [0.40000000, 1.00000000, 0.40000000],
  [0.40000000, 1.00000000, 0.60000000],
  [0.40000000, 1.00000000, 0.80000000],
  [0.40000000, 1.00000000, 1.00000000],
  [0.60000000, 0.20000000, 0.00000000],
  [0.60000000, 0.20000000, 0.20000000],
  [0.60000000, 0.20000000, 0.40000000],
  [0.60000000, 0.20000000, 0.60000000],
  [0.60000000, 0.20000000, 0.80000000],
  [0.60000000, 0.20000000, 1.00000000],
  [0.60000000, 1.00000000, 0.00000000],
  [0.60000000, 1.00000000, 0.20000000],
  [0.60000000, 1.00000000, 0.40000000],
  [0.60000000, 1.00000000, 0.60000000],
  [0.60000000, 1.00000000, 0.80000000],
  [0.60000000, 1.00000000, 1.00000000],
  [0.80000000, 0.55000000, 0.00000000],
  [0.80000000, 0.55000000, 1.00000000],
  [1.00000000, 0.00000000, 0.00000000],
  [1.00000000, 0.00000000, 0.20000000],
  [1.00000000, 0.00000000, 0.40000000],
  [1.00000000, 0.00000000, 0.60000000],
  [1.00000000, 0.00000000, 0.80000000],
  [1.00000000, 0.00000000, 1.00000000],
  [1.00000000, 1.00000000, 0.00000000],
  [1.00000000, 1.00000000, 0.20000000],
  [1.00000000, 1.00000000, 0.40000000],
  [1.00000000, 1.00000000, 0.60000000],
  [1.00000000, 1.00000000, 0.80000000],
  [1.00000000, 1.00000000, 1.00000000],
]
indices = [[0, 14, 12], [26, 40, 38], [46, 32, 38], [20, 6, 12], [0, 40, 14], [6, 0, 12], [40, 46, 38], [40, 26, 14], [32, 26, 38], [14, 20, 12], [1, 0, 40], [1, 40, 41], [2, 1, 41], [2, 41, 42], [3, 2, 42], [3, 42, 43], [4, 3, 43], [4, 43, 44], [5, 4, 44], [5, 44, 45], [41, 40, 46], [41, 46, 47], [42, 41, 47], [42, 47, 48], [43, 42, 48], [43, 48, 49], [44, 43, 49], [44, 49, 50], [45, 44, 50], [45, 50, 51], [47, 46, 32], [47, 32, 33], [48, 47, 33], [48, 33, 34], [49, 48, 34], [49, 34, 35], [50, 49, 35], [50, 35, 36], [51, 50, 36], [51, 36, 37], [33, 32, 26], [33, 26, 27], [34, 33, 27], [34, 27, 28], [35, 34, 28], [35, 28, 29], [36, 35, 29], [36, 29, 30], [37, 36, 30], [37, 30, 31], [27, 26, 15], [26, 14, 15], [28, 27, 16], [27, 15, 16], [29, 28, 17], [28, 16, 17], [30, 29, 18], [29, 17, 18], [31, 30, 19], [30, 18, 19], [15, 14, 20], [15, 20, 21], [16, 15, 21], [16, 21, 22], [17, 16, 22], [17, 22, 23], [18, 17, 23], [18, 23, 24], [19, 18, 24], [19, 24, 25], [21, 20, 6], [21, 6, 7], [22, 21, 7], [22, 7, 8], [23, 22, 8], [23, 8, 9], [24, 23, 9], [24, 9, 10], [25, 24, 10], [25, 10, 11], [7, 6, 0], [7, 0, 1], [8, 7, 1], [8, 1, 2], [9, 8, 2], [9, 2, 3], [10, 9, 3], [10, 3, 4], [11, 10, 4], [11, 4, 5], [5, 19, 13], [31, 45, 39], [51, 37, 39], [25, 11, 13], [5, 45, 19], [11, 5, 13], [45, 51, 39], [45, 31, 19], [37, 31, 39], [19, 25, 13]]
